config/routes.rb
RankingApp::Application.routes.draw do
  get "users/index"
  get "dogs/ranking"
  get "results/filtrado" => 'results#filtrado'
  devise_for :users

  root 'dogs#ranking'

  resources :dogs
  resources :users
  resources :exhibitions
  resources :results
  resources :points
  

  namespace :admin do
    get "results/filtrado" => 'results#filtrado'
    resources :users # Have the admin manage them here.
    resources :results
  end

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to  :user
  has_many :results, :dependent => :destroy

  mount_uploader :image, ImageUploader

  validates_presence_of :name, :birth_date
  validate :future_birth_date
  SEX = ['male', 'female']
  validates_inclusion_of :sex, in: SEX

  def future_birth_date
    if !birth_date.blank? and birth_date > Date.today
      errors.add(:birth_date, "can not be in the future")
    end
  end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]
  before_filter :set_user, only: [:new, :edit, :create, :update, :destroy]
  def index
    @theDogs = 'selected'
    @dogs = Dog.all
  end

  def new
    @dog = Dog.new
    authorize! :new, @dog
  end

  def create
    # @dog = @user.dogs.build(dog_params)
    @dog = Dog.new(dog_params)
    @dog.user = current_user
    authorize! :create, @dog

    if @dog.save
      flash[:notice] = 'Dog has been created.'
      redirect_to @dog
    else
      flash[:alert] = 'Dog has not been created.'
      render 'new'
    end
  end

  def show
    set_user
    @results = Result.where(dog_id: Dog.where(id: @dog.id))
    @points = Array.new(@results.count)

    i=0
      @points[i]=0
      for t in @results do
        @awards = Result.select(:award_id).where(dog_id: @dog.id, exhibition_id: t.exhibition.id).distinct
        @points[i] = Point.where(award_id: t.award_id,type_id: t.exhibition.type_id, year: t.exhibition.date.year).sum(:npoint)
        i=i+1
      end
  end

  def edit
    authorize! :edit, @dog
  end

  def update
    authorize! :update, @dog
    if @dog.update_attributes(dog_params)
      flash[:notice] = 'Dog has been updated.'
      redirect_to @dog
    else
      flash[:alert] = 'Dog has not been updated.'
      render 'edit'
    end
  end

  def destroy
    authorize! :destroy, @dog
    @dog.destroy
    flash[:notice] = "Dog has been deleted."
    redirect_to dogs_path
  end

  def ranking
    @dogs = Dog.all
    @points = Hash.new

    @dogs.each do |d|
      @results = Result.select(:award_id, :exhibition_id).where(dog_id: d.id, status: "Validated").distinct
      @points[d.name]=0
      for t in @results do
        @awards = Result.select(:award_id).where(dog_id: d.id, exhibition_id: t).distinct
        @points[d.name] = @points[d.name]+ Point.where(award_id: t.award_id,type_id: t.exhibition.type_id, year: t.exhibition.date.year).sum(:npoint)
      end
      @points[d.name] = [@points[d.name], d.image, d.sex, d.id]
    end
    @points =@points.sort_by{|a, b| b[0]}.reverse
  end

  private
    def dog_params
      params.require(:dog).permit(:sex, :titles, :name, :birth_date, :image)
    end

    def set_dog
      @dog = Dog.find(params[:id])
    end

    def set_user
      @user = current_user
    end
end

app/helpers/dogs_helper.rb
module DogsHelper

end

app/views/dogs/_dog.html.erb
<%= content_tag_for :tr, dog do %>
  <td><%= link_to image_tag(dog.image, class: "imageDog img-rounded"), dog_path(dog) %></td>
  <td><%= link_to dog.name, dog_path(dog) %></td>
  <% if user_signed_in? %>
  <td><% if !dog.user.nil? %>
        <%= link_to dog.user.email, user_path(dog.user) %>
      <% end %>
  </td>
  <% end %>

  <td><% if current_user.try(:admin?) || (current_user.try(:id) == dog.user_id && current_user.try(:cahoot?))  %>
        <%= link_to("Edit", edit_dog_path(dog)) %>
      <% end %>
  </td>
  <td><% if current_user.try(:admin?) || (current_user.try(:id) == dog.user_id && current_user.try(:cahoot?)) %>
        <%= link_to("Delete", dog, method: :delete, data: {confirm: 'Are you sure you want to delete this dog?'} ) %>
      <% end %>
  </td>
<% end %>

app/views/dogs/_form.html.erb
<% content_for :head do %>
    <%= javascript_include_tag 'filter', "data-turbolinks-track" => false  %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css" data-turbolinks-track="true">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<%end%>

<%= form_for @dog, html: {multipart: true, "data-ajax" => "false", class: "form" } do |f|  %>
    <div  class="alert alert-error msgAlert">
        <% @dog.errors.full_messages.each do |message| %>
            <p><%= message %></p>
        <% end %>
    </div>

    <div class="form-group">
      <%= f.label :image, class: "control-label" %>
      <%= f.file_field :image, class: "btn btn-default"%>
    </div>
    <div class="form-group">
      <%= f.label :sex, class: "control-label" %>
      <%= f.select :sex, [['Male', 'male'],['Female', 'female']], {prompt: 'Gender...'}, {class: "form-control", style: "width:10%;"}%>
    </div>
    <div class="form-group">
      <%= f.label :titles, class: "control-label" %>
      <%= f.text_area(:titles, rows: '2', class: "form-control") %>
    </div>
    <div class="form-group">
      <%= f.label :name, class: "control-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :birth_date, class: "control-label" %>
      <%#= f.datetime_field :birth_date, "id" => "datepicker", :value => (@dog.birth_date.blank? ? 'dd/mm/yyyy' :@dog.birth_date.strftime('%d/%m/%Y')) %>
      <%= f.text_field :birth_date, "id" => "datepicker", :value => (@dog.birth_date.blank? ? 'dd/mm/yyyy' :@dog.birth_date.strftime('%d/%m/%Y')), class: "form-control" %>
    </div>
    <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/dogs/edit.html.erb
<h2 class="title">Edit <%= @dog.name %></h2>
<%= render 'form' %>

app/views/dogs/index.html.erb
<% content_for :head do %>
    <%= javascript_include_tag "filter", "data-turbolinks-track" => false %>
<%end%>

<h2 class="title">Dogs' census of the "Asociación Española para el Fomento de la Raza Bulldog Francés"</h2>

<div class="input-group search"> <span class="input-group-addon">Search</span>
  <input id="filter" type="text" class="form-control" placeholder="Type here...">
</div>

<table class="table table-hover table-striped">
  <tr>
    <th>Photo</th>
    <th>Name</th>
    <% if user_signed_in? %>
      <th>Owner</th>
    <% end %>
    <th></th>
    <th></th>
  </tr>
  <tbody class="searchable">
    <%= render @dogs %>
  </tbody>
</table><br>

<% if can? :new, Dog  %>
  <%= link_to "New Dog", new_dog_path, class: "glyphicon glyphicon-plus link" %>
<% end %>

app/views/dogs/new.html.erb
<h2 class="title">New dog</h2>
<%= render 'form' %>

app/views/dogs/ranking.html.erb
<h2 class="title">Dogs' Ranking</h2>

<table class="table table-hover table-striped">
  <tr>
    <th>Points</th>
    <th>Photo</th>
    <th>Name</th>
    <th>Sex</th>
  </tr>
  <% @points.each do |k,v| %>
    <tr>
        <td><%= v[0] %></td>
        <td><%= link_to image_tag(v[1], class: "imageDog img-rounded"), dog_path(v[3]) %></td>
        <td><%= link_to k, dog_path(v[3]) %></td>
        <td><%= v[2] %></td>
    </tr>
  <% end %>
</table>

<!--<%# if can? :new, Dog  %>-->
<!--<%#= link_to "New Dog", new_dog_path, class: "glyphicon glyphicon-plus link" %>-->
<%# end %>

app/views/dogs/show.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag "dogs", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag 'filter' %>
<%end%>
<div class="row card">
    <div class="col-md-4">
      <%= image_tag(@dog.image_url, class: "imgDog img-thumbnail") if @dog.image.present? %>
      <% if current_user.try(:admin?) || ( current_user.try(:id) == @dog.user_id && current_user.try(:cahoot?)) %>
        <%= link_to "Edit Dog", edit_dog_path, class: "glyphicon glyphicon-pencil link editDog" %>
      <% end %>
    </div>
    <div class="col-md-5 textDog">
      <ul >
          <li class="information"><label class="fields">Name: </label><%= @dog.name %></li>
          <li class="information"><label class="fields">Sex: </label><%= @dog.sex %></br></li>
          <li class="information"><label class="fields">CH: </label><%= @dog.titles %></br></li>
          <li class="information"><label class="fields">Birthdate: </label><%= @dog.birth_date.strftime('%d/%m/%Y') %></br></li>
          <% if user_signed_in? %>
            <li class="information"><label class="fields">Owner: </label><%= link_to @dog.user.try(:email), user_path(@dog.user) %></br></li>
          <% end %>
      </ul>
    </div>

    <div class="col-md-3">
      <%= image_tag("huella.png", class: "footprint") %>
    </div>
    <div class="col-md-12 resultDog">
      <table class="table table-hover table-striped">
        <tr>
          <th colspan="8" style="text-align:center">Dog's results</th>
        </tr>

        <tr>
          <th>Exhibition</th>
          <th>Date</th>
          <th>Award</th>
          <th>Points</th>
          <th>Dog</th>
          <th>Status</th>
          <th></th>
          <th></th>

        </tr>

        <% i=0 %>
        <% @results.each do |result| %>
            <tr>
              <td><%= link_to result.exhibition.try(:name), exhibition_path(result.exhibition) %>
              </td>
              <td><%= result.exhibition.try(:date).strftime('%d/%m/%Y') %></td>
              <td><%= result.award.try(:award) %></td>
              <td><%= @points[i] %></td>
              <td><%= result.dog.try(:name) %></td>
              <td><%= result.status %></td>
              <td><% if can? :edit, result %>
                    <%= link_to("Edit", edit_admin_result_path(result) ) %>
                <% end %>
              </td>
              <td><% if can? :destroy, result %>
                    <% if result.status == 'Pending' || result.status == 'Rejected' || current_user.try(:admin?) %>
                      <%= link_to("Delete", result, method: :delete, data: {confirm: 'Are you sure you want to delete this result?'} ) %>
                    <% end %>
                <% end %>
              </td>
              <% i= i + 1 %>
            </tr>
        <% end %>
      </table></br>
    </div>
</div>