config/routes.rb
RankingApp::Application.routes.draw do
  get "users/index"
  get "dogs/ranking"
  get "results/filtrado" => 'results#filtrado'
  devise_for :users

  root 'dogs#ranking'

  resources :dogs
  resources :users
  resources :exhibitions
  resources :results
  resources :points
  

  namespace :admin do
    get "results/filtrado" => 'results#filtrado'
    resources :users # Have the admin manage them here.
    resources :results
  end

end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :exhibition
  belongs_to :award
  belongs_to :dog

  #after_create :
  has_many :points, through: :award

  validates_presence_of :exhibition_id, :award_id, :dog_id
  STATUS = ['Pending','Validated','Rejected']
  validates_inclusion_of :status, in: STATUS
  validate :not_celebrated_exhibition

  def not_celebrated_exhibition
    if !exhibition_id.blank? and exhibition.date > Date.today
      errors.add(:exhibition, "hasn't been celebrated")
    end
  end

end

app/controllers/admin/results_controller.rb
class Admin::ResultsController < ApplicationController
  before_filter :authorize_admin!, except: [:show]
  before_action :set_result, only: [:show, :edit, :update, :destroy]
  def index
    @adminResults = 'selected'
    @results = Result.all
  end

  def new
    @result = Result.new
  end

  def create
    @result = Result.new(result_params)

    if @result.save
      flash[:notice] = 'Result has been created.'
      redirect_to admin_results_path
    else
      flash[:alert] = 'Result has not been created.'
      render 'new'
    end
  end

  def show
  end

  def edit
    @selected = @result.exhibition_id
    @selectedDog = @result.dog_id
    @selectedAward = @result.award_id
    aux = {}
    aux[:exhibition] = @selected
    @points = Point.search(aux).select(:award_id)
  end

  def update
    if @result.update_attributes(result_params)
      #set_result_user
      @user = User.where(id: Dog.where(id: @result.dog_id).select(:user_id)).first
      ResultMailer.edit_result_by_admin(@user,@result).deliver
      flash[:notice] = "Result has been updated. A message with the result's link has been sent to user email address"
      redirect_to admin_results_path
    else
      flash[:alert] = 'Result has not been updated.'
      render 'edit'
    end
  end

  def destroy
    @result.destroy
    flash[:notice] = "Result has been deleted."
    redirect_to admin_results_path
  end

  def filtrado
    @result = Result.new
    if params[:id] != 'new'
      set_result
      @selectedDog = @result.dog_id
      @selectedAward = @result.award_id
    end
    @selected = params[:exhibition]

    @points = Point.search(params).select(:award_id)
    respond_to do |format|
      format.js
    end

  end


  private
  def result_params
    params.require(:result).permit(:exhibition_id, :award_id, :dog_id, :status)
  end

  def set_result
    @result = Result.find(params[:id])
  end

  def set_result_user
    @user = User.find(@result.dog_id)
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_filter :authorize_admin!, only: [:edit, :update]
  before_action :set_result, only: [:show, :edit, :update, :destroy]


  def index
    set_user
    @results = Result.where(dog_id: Dog.where(user_id: @user))
    @dogs = Dog.where(user_id: @user)
    @points = Array.new(@dogs.count)

    i=0
    @dogs.each do |d|
      @points[i]=0
      for t in @results do
        @awards = Result.select(:award_id).where(dog_id: d.id, exhibition_id: t.exhibition.id).distinct
        @points[i] = Point.where(award_id: t.award_id,type_id: t.exhibition.type_id, year: t.exhibition.date.year).sum(:npoint)
        i=i+1
      end
    end
    @myResults = 'selected'
    authorize! :index, Result
  end

  def new
    @result = Result.new
    @exhib = params[:exhibition_id]
    authorize! :new, Result
  end

  def create
    @result = Result.new(result_params)
    @exhib = params[:exhibition]
    if @result.status.blank?
      @result.status = 'Pending'
    end
    authorize! :create, Result
    if @result.save
      ResultMailer.create_result(current_user, @result).deliver
      set_admins
      ResultMailer.create_result_to_admin(current_user, @result, @admins).deliver
      flash[:notice] = "Result has been created. A message with the result's link has been sent to your email address"
      redirect_to results_path
    else
      flash[:alert] = 'Result has not been created.'
      render 'new'
    end
  end

  def show
    authorize! :show, Result
  end

  def edit
    authorize! :edit, Result
  end

  def update
    if @result.update_attributes(result_params)
      #set_result_user
      #@owner = Dog.where(id: @result.dog_id)
      @user = User.where(id: Dog.where(id: @result.dog_id).select(:user_id)).first
      ResultMailer.edit_result_by_admin(@user,@result).deliver
      flash[:notice] = "Result has been updated. A message with the result's link has been sent to user email address"
        redirect_to results_path
    else
      flash[:alert] = 'Result has not been updated.'
      render 'edit'
    end
  end

  def destroy
    authorize! :destroy, Result
    authenticate_user!
    if @result.status == 'Pending' || @result.status == 'Rejected'
      @result.destroy
      flash[:notice] = "Result has been deleted."
      if current_user.admin?
        redirect_to admin_results_path
      else
        redirect_to results_path
      end
    elsif current_user.admin? @result.status == 'Validated'
      @result.destroy
      flash[:notice] = "Result has been deleted."
      redirect_to admin_results_path
    else
      flash[:alert] = "Result has not been deleted."
      redirect_to results_path
    end
  end

  def filtrado
    @result = Result.new
    @points = Point.search(params).select(:award_id)
    @selected = params[:exhibition]
    respond_to do |format|
      format.js
    end

  end


  private
  def result_params
    params.require(:result).permit(:exhibition_id, :award_id, :dog_id, :status)
  end

  def set_result
    @result = Result.find(params[:id])
  end

  def set_result_user
    @user = User.find(@result.dog_id)
  end

  def set_user
    @user = current_user.id
  end

  def set_admins
    @admins = User.where(admin: 'true')
  end
end

app/views/results/_award.html.erb
<%= form_for @result, html: {multipart: true, "data-ajax" => "false", class: "form"} do |f| %>
    <div  class="alert alert-error msgAlert">
      <% @result.errors.full_messages.each do |message| %>
          <p><%= message %></p>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :exhibition_id, class: "control-label" %>
      <%= f.collection_select(:exhibition_id,  Exhibition.all, :id, :name, {:selected =>@selected},{class: "form-control", style: "width:20%;", id:"exhibition", onchange: 'showAwards()'}) %>
    </div>
    <div id="awards" class="form-group">
      <%= f.label :award_id, class: "control-label" %>
      <%= f.collection_select :award_id, Award.where(id: @points), :id, :award, {prompt: 'Award...'}, {class: "form-control", style: "width:20%;"} %>
    </div>
    <div class="form-group">
      <%= f.label :dog_id, class: "control-label" %>
      <%= f.collection_select :dog_id, Dog.find_all_by_user_id(current_user), :id, :name, {prompt: 'Dog...'}, {class: "form-control", style: "width:20%;"} %>
    </div>

    <%= f.submit :class => "btn btn-primary" %>

<% end %>

app/views/results/_form.html.erb
<div id="formulario">
<%= form_for @result, html: {multipart: true, "data-ajax" => "false", class: "form"} do |f| %>
    <div  class="alert alert-error msgAlert">
        <% @result.errors.full_messages.each do |message| %>
            <p><%= message %></p>
        <% end %>
    </div>

    <div class="form-group">
      <%= f.label :exhibition_id, class: "control-label" %>
      <%= f.collection_select(:exhibition_id, Exhibition.all, :id, :name,{ prompt: 'Exhibition...', :selected =>@selected},{class: "form-control", style: "width:20%;", id:"exhibition", onchange: 'showAwards()'}) %>
    </div>
    <div id="awards" class="form-group">
      <%= f.label :award_id, class: "control-label" %>
      <%= f.collection_select :award_id, Award.where(id: @points), :id, :award, {prompt: 'Award...'}, {class: "form-control", style: "width:20%;"} %>
    </div>
    <div class="form-group">
      <%= f.label :dog_id, class: "control-label" %>
      <%= f.collection_select :dog_id, Dog.find_all_by_user_id(current_user), :id, :name, {prompt: 'Dog...'}, {class: "form-control", style: "width:20%;"} %>
    </div>

    <%= f.submit :class => "btn btn-primary" %>
<% end %>
</div>

app/views/results/_result.html.erb
<% i=0 %>
<%= content_tag_for :tr, result do %>
    <td><%= result.exhibition.try(:name) %></td>
    <td><%= result.exhibition.try(:date).strftime('%d/%m/%Y') %></td>
    <td><%= result.award.try(:award) %></td>
    <td><%= @points[i] %></td>
    <td><%= result.dog.try(:name) %></td>
    <td><%= result.status %></td>
    <td><% if result.status == 'Pending' || result.status == 'Rejected' || current_user.admin? %>
          <%= link_to("Delete", result, method: :delete, data: {confirm: 'Are you sure you want to delete this result?'} ) %>
        <% end %>
    </td>
    <% i= i + 1 %>
<% end %>

app/views/results/edit.html.erb
<h2 class="title">Edit result</h2>
<%= render 'form' %>

app/views/results/filtrado.js.erb
$("#formulario").html("<%= escape_javascript render( partial: "form") %>");

app/views/results/index.html.erb
<h2 class="title">My dogs' results</h2>
<table class="table table-hover table-striped">
  <tr>
    <th>Exhibition</th>
    <th>Date</th>
    <th>Award</th>
    <th>Points</th>
    <th>Dog</th>
    <th>Status</th>
    <th></th>
    <th></th>
  </tr>


  <% i=0 %>
  <% @results.each do |result| %>
      <tr>
      <td><%= link_to result.exhibition.try(:name), exhibition_path(result.exhibition) %></td>
      <td><%= result.exhibition.try(:date).strftime('%d/%m/%Y') %></td>
      <td><%= result.award.try(:award) %></td>
      <td><%= @points[i] %></td>
      <td><%= link_to result.dog.try(:name), dog_path(result.dog) %></td>
      <td><%= result.status %></td>
      <td><% if can? :edit, result %><%= link_to "Edit", edit_admin_result_path(result) %><% end %></td>
      <td><% if can? :destroy, result %>
            <% if result.status == 'Pending' || result.status == 'Rejected' || current_user.try(:admin?) %>
              <%= link_to("Delete", result, method: :delete, data: {confirm: 'Are you sure you want to delete this result?'} ) %>
            <% end %>
        <% end %>
      </td>
      <% i= i + 1 %>
      </tr>
  <% end %>

</table></br>
<% if can? :new, Result %>
  <%= link_to("New Result", new_result_path, class: "glyphicon glyphicon-plus link" ) %>
<% end %>

app/views/results/new.html.erb
<h2 class="title">New result</h2>
<%= render 'form' %>

app/views/results/show.html.erb
<h2 class="title">Results of <%= @result.dog.user.email %></h2>

<table  class="table table-hover table-striped">
  <tr>
    <th>Exhibition</th>
    <th>Award</th>
    <th>Dog</th>
    <th>Status</th>
  </tr>
  <tr>
    <td><%= @result.exhibition.name %></td>
    <td><%= @result.award.award %></td>
    <td><%= @result.dog.name %></td>
    <td><%= @result.status %></td>
  </tr>
</table>
<% if  can? :edit, Result %>
    <%= link_to("Edit Result", edit_admin_result_path, class: "glyphicon glyphicon-pencil link")  %>
<% end %>