config/routes.rb
RankingApp::Application.routes.draw do
  get "users/index"
  get "dogs/ranking"
  get "results/filtrado" => 'results#filtrado'
  devise_for :users

  root 'dogs#ranking'

  resources :dogs
  resources :users
  resources :exhibitions
  resources :results
  resources :points
  

  namespace :admin do
    get "results/filtrado" => 'results#filtrado'
    resources :users # Have the admin manage them here.
    resources :results
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>RankingApp</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "filter", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body class="page">
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid bigBar">
    <div id="bar" class="container">
        <div id="header1" class="navbar-header">
            <a class="navbar-brand aefrbf" href="/"><%= image_tag "aefrbf.jpg"%></a>
        </div>
        <div id="header2" class="collapse navbar-collapse">
            <ul id="menu" class="nav navbar-nav">
                <li id=<%= @theDogs%>><%= link_to "Dogs", dogs_path, {class:'textHeader'}  %></li>
                <% if user_signed_in? %>
                    <% if current_user.try(:admin?) %>
                      <li id=<%= @adminUsers%>><%= link_to "Users", admin_users_path, class:'textHeader' %></li>
                      <li id=<%= @adminResults%>><%= link_to "Results", admin_results_path, class:'textHeader' %></li>
                    <% end %>
                    <li id=<%= @myProfile%>><%= link_to "My profile", user_path(current_user), class:'textHeader' %></li>
                    <li id=<%= @myResults%>><%= link_to "My results",results_path, class:'textHeader' %></li>
                    <li id=<%= @allExhibitions%>><%= link_to "Exhibitions", exhibitions_path, class:'textHeader' %></li>
                    <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, class:'textHeader' %></li>
                    <li><p class="navbar-text navbar-right textSign">Signed in as <%= current_user.email %></p></li>
                <% else %>
                    <li id=<%= @signUp%>><%= link_to "Sign up", new_user_registration_path, class:'textHeader' %></li>
                    <li id=<%= @signIn%>><%= link_to "Sign in", new_user_session_path, class:'textHeader' %></li>
                <% end %>
            </ul>
        </div>
    </div>
  </div>
</nav>


<%# flash.each do |key, value| %>
    <!--<div class="flash" id="<%#= key %>" >-->
      <%#= value %>
    <!--</div>-->
<%# end %>

<div class="container">
  <% if current_user.try(:admin?) %>
    <p class="textSign2">Signed in as <%= current_user.email %></p>
  <% end %>

  <p class="msgNotice"><%= notice %></p>

  <p class="msgAlert"><%= alert %></p>
    <%= yield %>
</div>

<footer>
  <div class="container">
    <%= image_tag "bulldogs.gif", :id => "gif"%>
  </div>
</footer>

</body>

</html>